{"uuid": "4e3c8eec-68cb-4c47-be6f-3ee03e15be82", "children": ["34635ff6-bb39-42a1-be5d-26d6750f16b0"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=115.0.5790.170)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0098A813+48355]\n\t(No symbol) [0x0091C4B1]\n\t(No symbol) [0x00825358]\n\t(No symbol) [0x0080D293]\n\t(No symbol) [0x0086E37B]\n\t(No symbol) [0x0087C473]\n\t(No symbol) [0x0086A536]\n\t(No symbol) [0x008482DC]\n\t(No symbol) [0x008493DD]\n\tGetHandleVerifier [0x00BEAABD+2539405]\n\tGetHandleVerifier [0x00C2A78F+2800735]\n\tGetHandleVerifier [0x00C2456C+2775612]\n\tGetHandleVerifier [0x00A151E0+616112]\n\t(No symbol) [0x00925F8C]\n\t(No symbol) [0x00922328]\n\t(No symbol) [0x0092240B]\n\t(No symbol) [0x00914FF7]\n\tBaseThreadInitThunk [0x766E7D59+25]\n\tRtlInitializeExceptionChain [0x7715B79B+107]\n\tRtlClearBits [0x7715B71F+191]\n\n", "trace": "  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\makde\\Desktop\\SW Testing\\Pytest framework\\CredKart_pytest_project 31-07-2023\\CredKart_Pytest_Project - Copy\\testCases\\conftest.py\", line 38, in setup\n    driver.maximize_window()\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 498, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1691475656958, "stop": 1691475663538}], "start": 1691475656958, "stop": 1691475665627}